# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fcgi}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{saks}]
  s.date = %q{2011-08-08}
  s.description = %q{FastCGI is a language independent, scalable, open extension to CGI that provides high performance without the limitations of server specific APIs. This version aims to be compatible with both 1.8x and 1.9x versions of Ruby}
  s.email = %q{saksmlz@gmail.com}
  s.extensions = [%q{ext/fcgi/extconf.rb}]
  s.extra_rdoc_files = [
    "ChangeLog",
    "LICENSE",
    "README.rdoc",
    "README.signals"
  ]
  s.files = [
    ".config",
    ".document",
    "ChangeLog",
    "LICENSE",
    "README.rdoc",
    "README.signals",
    "Rakefile",
    "VERSION",
    "ext/fcgi/MANIFEST",
    "ext/fcgi/Makefile",
    "ext/fcgi/extconf.rb",
    "ext/fcgi/fcgi.c",
    "lib/fcgi.rb",
    "fcgi.gemspec",
    "test/helper.rb",
    "test/test_fcgi.rb"
  ]
  s.homepage = %q{http://github.com/saks/fcgi}
  s.require_paths = [%q{lib}, %q{ext}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{FastCGI library for Ruby.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

