# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-fcgi}
  s.version = "0.8.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{saks}]
  s.date = %q{2011-07-18}
  s.description = %q{FastCGI is a language independent, scalable, open extension to CGI that provides high performance without the limitations of server specific APIs. For more information, see http://www.fastcgi.com/. This is the fork of fcgi implementation for ruby but with ruby1.9 - ruby1.9.1 compability}
  s.email = %q{saksmlz@gmail.com}
  s.extensions = [%q{ext/fcgi/extconf.rb}]
  s.extra_rdoc_files = [
    "ChangeLog",
    "LICENSE",
    "README",
    "README.rdoc",
    "README.signals"
  ]
  s.files = [
    ".config",
    ".document",
    "ChangeLog",
    "InstalledFiles",
    "LICENSE",
    "README",
    "README.rdoc",
    "README.signals",
    "Rakefile",
    "VERSION",
    "ext/fcgi/MANIFEST",
    "ext/fcgi/Makefile",
    "ext/fcgi/extconf.rb",
    "ext/fcgi/fcgi.c",
    "install.rb",
    "lib/fcgi.rb",
    "test/helper.rb",
    "test/test_fcgi.rb"
  ]
  s.homepage = %q{http://github.com/saks/fcgi}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{FastCGI library for Ruby.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

